# Combined spring configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plataforma_clases
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: framework

google:
  calendar:
    api:
     oauth:
      client:
        id: ${GOOGLE_CLIENT_ID}
        secret: ${GOOGLE_CLIENT_SECRET}
    credentials:
     file:
        path: classpath:google-calendar-credentials.json

#ai:
# api:
#    endpoint: http://localhost:8080/api/ai # O la URL real de tu API de IA
#    key: YourAIAPIKeyHere # Reemplaza con tu clave de API real
    
jwt:
  secret: JjdP3kF5rDvhReN48gak6mfF3JMWoeJXtklmGzxBkwVDRoVX7MtxJD5Z+z6KIR0eKTYiATc9bdUrqgQZlPOaQA==
  expiration:
    ms: 86400000
